version: "3"
services:
  api:
   build:
      context: ./
      dockerfile: Dockerfile.dev
   ports:
     - 3080:3080
   container_name: tesis-backend
   restart: unless-stopped
   networks:
     - tesis-stack-net
   volumes:
    - ./:/usr/app/src
    - ./uploads:/app/uploads
   depends_on:
    - db
   links:
    - db

  db:
    image: mongo:5.0.8
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    container_name: tesis-db
    restart: unless-stopped
    networks:
      - tesis-stack-net
    volumes:
      - mongo-data:/data/db

networks:
  tesis-stack-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local