# Stage 1 - build
FROM node:19
WORKDIR /app
# Install dependencies
RUN mkdir uploads
RUN mkdir transcriptions
# copy the files to the uploads directory
ADD uploads app/uploads
# Install dependencies
COPY package*.json ./
# Copy the rest of the files
COPY . . 
# Install Dependencies
RUN npm install
ADD uploads /app/uploads
COPY . .
EXPOSE 3080
CMD ["npm", "run", "dev"]